config/routes.rb
SampleApp::Application.routes.draw do

   root to: 'static_pages#home'

   resources :users
   resources :sessions, only: [:new, :create, :destroy]
   resources :stocks, only: [:index]
   resources :transactions

   match '/transactions', to: 'transactions#index'
   match '/signup',  to: 'users#new'
   match '/signin',  to: 'sessions#new'
   match '/signout', to: 'sessions#destroy', via: :delete

   match '/about',   to: 'static_pages#about'
   match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_flash_alerts.html.erb
<div id = "flash_alerter">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar  navbar-fixed-bottom navbar-inverse">
  <small>
    <a href="/">Demo app presentation</a>
    by Ayush Ladia
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <% if signed_in? %>
            <%= link_to "stocometer", current_user, id: "logo" %></li>
          <% else %>
            <%= link_to "stocometer", root_path, id: "logo" %></li>
          <% end %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Home", current_user %></li>
          <% else %>
            <li><%= link_to "Home", root_path %></li>
          <% end %>
          <% if signed_in? %>
            <li><%= link_to "stocks", stocks_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Transactions", transactions_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>stocometer</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_alerts' , :flash => flash %>
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
    <div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>